#!/bin/sh

sudo apt install \
   libgtk-4-dev \
   libadwaita-1-dev \
   libshumate-dev \
   libgstreamer1.0-dev \
   gstreamer1.0-plugins-good \
   libspeechd-dev \
   speech-dispatcher \
   gpsd \
   gpsd-clients \
   cmake \
   clang
